### ISSUE TITLE
Fluid template files could not be loaded

### ISSUE THREAD

**Issue by instruccionesaldorso** [NamelessCoder/typo3-cms-fluid-precompiler-module#11]
Using a clean fresh TYPO3 8.7.19, the next error appears when trying to compile all fluid templates.
It seems core module "typo3/cms-scheduler" causes this conflict.

![screenshot-v8 local-2018 09 19-10-03-37](https://user-images.githubusercontent.com/10220356/45739507-7ccc2200-bbf3-11e8-99ed-c23e3bb8ef02.png)

**Comment by instruccionesaldorso** [comment]
Here in the construct() it is specified the path to the partials:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php#L161
But it seems it's not being taken into account.

**Comment by instruccionesaldorso** [comment]
If I unload EXT:scheduler, the same happens with EXT:install:

The Fluid template files "/var/www/Test/v8/web/typo3/sysext/install/Resources/Private/Partials/StepCounter.html", "/var/www/Test/v8/web/typo3/sysext/install/Resources/Private/Partials/StepCounter" could not be loaded.

**Comment by instruccionesaldorso** [comment]
Any news regarding this?

**Comment by mbrodala** [comment]
@instruccionesaldorso See #12

**Comment by NamelessCoder** [comment]
Closing this issue in favor of #12 which has slightly more debugging info. See my message in that issue.
