### ISSUE TITLE
EXT:install Fluid namespace not found

### ISSUE THREAD

**Issue by romm** [NamelessCoder/typo3-cms-fluid-precompiler-module#2]
**TYPO3** 8.7.2
**EXT:cms_fluid_precompiler_module** 1.0.0

When compiling **all** extensions with **additional reports enabled**, an exception is thrown that stops the compilation:

After some digging, it seems to come from [Step.html](https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_8-7-2/typo3/sysext/install/Resources/Private/Layouts/Step.html#L13) from `EXT:install`. The `i` namespace seems not to be resolved.

```
Fluid parse error in template , line 1 at character 1. Error: Unkown Namespace: &lt;i:constant name=&quot;TYPO3_version&quot; /&gt; (error code 0). Template source chunk: 
```

Compiling only `EXT:install` leads to the same error.

I don't know how new Fluid Standalone usage in TYPO3 v8+ adds default namespaces, but it seems not to be done correctly in this particular situation.

The source point error from the extension is [FluidPrecompilerService:73](https://github.com/NamelessCoder/typo3-cms-fluid-precompiler-module/blob/1.0.0/Classes/Service/FluidPrecompilerService.php#L73).

**Comment by NamelessCoder** [comment]
See https://review.typo3.org/#/c/53375/ which came about because of this. Once that's merged and hopefully backported, that last template will compile. I'm not even sure it's used :)

**Comment by romm** [comment]
Hehe indeed that was the hotfix I also did on my dev installation. :)
