### ISSUE TITLE
Multiple PHP Warnings "A non-numeric value encountered in ..." encounter

### ISSUE THREAD

**Issue by ghost** [NamelessCoder/typo3-cms-fluid-precompiler-module#7]
The Typo3 Backend Log shows a huge amount of php warnings.

![image](https://user-images.githubusercontent.com/38243272/38545930-875e81e4-3cab-11e8-9b66-9b0fa1b58aaf.png)

It looks like that problem lies in fluid package itself, but those warnings appeared only when i installed this extension.

Regards
Julian

**Comment by NamelessCoder** [comment]
This is a known issue in Fluid itself - a solution is proposed on https://github.com/TYPO3/Fluid/pull/369. The reason you see it only when compiling this way is the lack of variables created in runtime: the compiler is not aware which variables you used when rendering each template, it can only be aware of the template itself. See issue for possible workaround.
