### ISSUE TITLE
Typo3 Error during precompilation - Files not found

### ISSUE THREAD

**Issue by ghost** [NamelessCoder/typo3-cms-fluid-precompiler-module#8]
If i choose an extension in the backend module, it will produce a Typo3 Error message which say that no partials were found... even if this extension is a core extension.

![image](https://user-images.githubusercontent.com/38243272/38546145-29105d14-3cac-11e8-8051-7ae73db02039.png)

I think the problem is that the precompiler doesn't respect the whole path of the render viewhelper (the same happens for the layouts)

![image](https://user-images.githubusercontent.com/38243272/38546486-19a60cb0-3cad-11e8-9e8a-8ac559caf7f4.png)

Regards
Julian

**Comment by NamelessCoder** [comment]
https://github.com/TYPO3/Fluid/pull/348 may be related - this patch is included in TYPO3 8.7.11 I believe it was, so please make sure you have the latest version installed.

**Comment by ghost** [comment]
The version is 8.7.12 (a fresh install)

And if i look inside the Fluid source code (vendor folder), the mentioned patch is there...

**Comment by NamelessCoder** [comment]
I have a fix for this issue. But it exposed some other annoyances, so I have to take a little tour down the rabbit hole.

**Comment by NamelessCoder** [comment]
The next release of Fluid will take care of this problem. I'm going to take the liberty of closing this issue pre-emptively. If you desperately need to test it, you can temporarily require `typo3fluid/fluid:dev-master`.

**Comment by ghost** [comment]
Thank you very much! I think i can wait till the next official bugfix version of the Typo3 Core :)
