### ISSUE TITLE
Failure during compilation

### ISSUE THREAD

**Issue by instruccionesaldorso** [NamelessCoder/typo3-cms-fluid-precompiler-module#9]
TYPO3 v8.7.16
EXT:typo3-cms-fluid-precompiler-module master branch
When trying to compile all extension keys, I receive the next error (see screenshot attached).

![screenshot-2018 07 16-09-50-32](https://user-images.githubusercontent.com/10220356/42748365-3fa9bafe-88e0-11e8-9dcc-8d820f18cc81.png)

**Comment by mbrodala** [comment]
Sounds like this is the same issue as #8

**Comment by NamelessCoder** [comment]
Indeed, a duplicate of #8 - let's continue there :)
